import type { Metadata } from "next";
import { Providers } from "./providers";
import { Inter } from "next/font/google";
import { Box} from "@chakra-ui/react";
import { Text } from "@chakra-ui/react";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Notes App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Box bgColor={"lightblue"} padding={"10px"} >
          <Text color={"black"} fontSize={"30px"} fontWeight={"bold"} marginLeft={30}>Notes App </Text>
        </Box>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
